### ISSUE TITLE
Build prysm with Bazel

### ISSUE THREAD

**Issue by asymmetric** [nix-community/ethereum.nix#171]
Upstream [recommends](https://docs.prylabs.network/docs/reading/bazel#with-go) building release binaries with Bazel.

**Comment by sambacha** [comment]
This is a valid concern as the Prysm team claims 6-8% client performance improvement using Bazel for building rather than the native Go compiler. wdyt @brianmcgee ?

**Comment by asymmetric** [comment]
@sambacha where did you get those estimates from?

**Comment by brianmcgee** [comment]
It seems prudent to build it as recommended. It works fine as is, I've been testing with it for weeks now. But we should match upstream. All things being equal I should have time nearer the end of this week to have a look into this.

**Comment by aldoborrero** [comment]
In terms of switching to Bazel we already had some conversations on Matrix about this with @asymmetric

I'm about to add a couple of notes that summarize the conversation we had about the subject, so we can discuss:

- `buildBazelPackage` is heavily under-documented on nixpkgs.
- Prysm uses a precompiled version of `bls`, whilst we pass ours built from source to `buildInputs`. `buildInputs` will be used for providing the `.h` files to `bls-eth-go-binary` library and [the precompiled one is imported in the code and used by the go binary](https://github.com/prysmaticlabs/prysm/blob/d1c45b44beb22858852e38f473a23e0f6a4310ec/crypto/bls/herumi/init.go#L3). So, as long as both are on the same version, it shouldn't be a problem ([here are the versions pinned by bazel](https://github.com/prysmaticlabs/prysm/blob/develop/third_party/herumi/herumi.bzl)). Right now, on `ethereum.nix` there's no release policy for libs, but it's a thing at some point we should also address (also, at least, in a similar way that `nixpkgs` provides).
- Prysm uses `clang` instead of `gcc` for releases (we can rely on `pkgs.clangStdenv`).
- [Prysm also patches some deps](https://github.com/prysmaticlabs/prysm/tree/develop/third_party) (including Geth), but, apparently, those patches are there to make things work with Bazel, it can be ignored when using go.

I'm not entirely sure if switching to Bazel is going to provide the performance "benefits" they claim as those can be attributed mainly to `clang`, but certainly, there's an argument to be made in reference to the fewer deviations from what they build we do, the better.

**Comment by aldoborrero** [comment]
For now, I'm still leaning towards we shouldn't spend our time switching to Bazel. So I'm going to close this issue and we can refer back in the future.
