### ISSUE TITLE
Support building/running `prysm` for `aarch64-linux`

### ISSUE THREAD

**Issue by PoisonPhang** [nix-community/ethereum.nix#284]
Currently, `prysm` only targets `x86_64-linux` adding targets for `aarch64-linux` and more would be helpful.

**Comment by aldoborrero** [comment]
Hi, @PoisonPhang we haven't enabled support for other architectures yet as we haven't tested those so well (for myself, I'm only running on `x86_64-linux` for now), but we can add those pretty easily. I know Prysm supports `aarch64-linux`, so feel free to add a PR with the change.

Maybe we also need to tweak the build system with the recommended env variable `export PRYSM_ALLOW_UNVERIFIED_BINARIES=1` when targeting arm as recommended on their [FAQ](https://docs.prylabs.network/docs/install/install-with-script#frequently-asked-questions).

**Comment by PoisonPhang** [comment]
Switching to Bazel is also in the near future, yes? @aldoborrero 

If I can find the time - I might try and tackle both this issue and the bazel upgrade.

**Comment by aldoborrero** [comment]
@PoisonPhang in terms of switching to Bazel we already had some conversations on Matrix about this with @asymmetric (we created issue #171 to discuss more on the open there but never happened as all of us focused on different matters afterward).

I'm about to add a couple of notes that summarize the conversation we had about the subject, so we can discuss:

- `buildBazelPackage` is heavily under-documented on nixpkgs.
- Prysm uses a precompiled version of `bls`, whilst we pass ours built from source to `buildInputs`. `buildInputs` will be used for providing the `.h` files to `bls-eth-go-binary` library and [the precompiled one is imported in the code and used by the go binary](https://github.com/prysmaticlabs/prysm/blob/d1c45b44beb22858852e38f473a23e0f6a4310ec/crypto/bls/herumi/init.go#L3). So, as long as both are on the same version, it shouldn't be a problem ([here are the versions pinned by bazel](https://github.com/prysmaticlabs/prysm/blob/develop/third_party/herumi/herumi.bzl)). Right now, on `ethereum.nix` there's no release policy for libs, but it's a thing at some point we should also address (also, at least, in a similar way that `nixpkgs` provides).
- Prysm uses `clang` instead of `gcc` for releases (we can rely on `pkgs.clangStdenv`).
- [Prysm also patches some deps](https://github.com/prysmaticlabs/prysm/tree/develop/third_party) (including Geth), but, apparently, those patches are there to make things work with Bazel, it can be ignored when using go.

I'm not entirely sure if switching to Bazel is going to provide the performance "benefits" they claim, but certainly, there's an argument to be made in reference to the fewer deviations from what they build we do, the better.

If you want, we can keep discussing bazel-related matters in #171 and I'll assign both issues to you.

**Comment by aldoborrero** [comment]
Closed by #386
