### ISSUE TITLE
mkGeth is not compatible with nix-update

### ISSUE THREAD

**Issue by brianmcgee** [nix-community/ethereum.nix#70]
Some aspect of how we are building the geth related packages with `mkGeth` is preventing it from working nicely with `nix-update`.

**Comment by aldoborrero** [comment]
Mmm, probably it's because of how the tool is coded; remember that `mkGeth` is a custom function, and I bet `nix-update` will search for `mkDerivation` .

At this point, I'm not entirely sure if we should remove `mkGeth` entirely and, for each `geth` instance, define it as it should with proper `buildGoModules`.

**Comment by brianmcgee** [comment]
I think it's better to keep it simple and compliant with `nix-update`. We're not saving much with `mkGeth`

**Comment by aldoborrero** [comment]
I'll proceed to remove it but after #71 is merged.
